apiVersion: v1
kind: Secret
metadata:
  name: thanos-objstore-config
  namespace: observability
type: Opaque
stringData:
  objstore.yml: |
    type: S3
    config:
      bucket: thanos
      endpoint: garage.garage.svc.cluster.local:3900
      access_key: change-this
      secret_key: change-this
      insecure: true
      signature_version2: false
      http_config:
        idle_conn_timeout: 90s
        response_header_timeout: 2m
        insecure_skip_verify: true
---
# Note: Update the access_key and secret_key to match your Garage credentials
#
# To create a key in Garage:
#   garage key new --name thanos-key
#   garage key info thanos-key
#
# To create the bucket:
#   garage bucket create thanos
#   garage bucket allow --read --write thanos --key thanos-key
